### ISSUE TITLE
[Unity3d] How to rebuild the project from Xamarin?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/Parse-SDK-dotNET#196]
Is there any guide to download and build this project on my own using Xamarin Project as I want to be able to use the stripping symbols in Unity3d. I'm thinking to take away the Parse Push as I'm not using it right now.

Thank you.

**Comment by richardjrossiii** [comment]
You cannot build the SDK project in Xamarin due to a bug with how Xamarin builds search paths for projects. This has been discussed in detail here: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-182609656. I'd recommend using Visual Studio CE to do your builds, or fork the SDK to do manual path expansion for every project you care about.
