### ISSUE TITLE
Possible to talk to 2 separate parse servers in 1 application?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/Parse-SDK-dotNET#220]
Hello, the ParseClient.Initialize step seems to be something that's done once and only once with this SDK.  I can't figure out any way, for example, to talk to 2 different parse server installations in a single console application using this SDK.  Am I missing something?

**Comment by AndrewLane** [comment]
Following up on this...

**Comment by richardjrossiii** [comment]
There is currently no way to do this, no. The parse architecture is very singleton-focused, and it's one of the more painful things, I agree. However, at this point in Parse's lifecycle, such a rewrite to be less singleton-based isn't really practical. You could run two builds of parse side by side, with different namespaces/assembly names, which should mostly work, though you may run into some odd edge cases where we might refer to classes by name instead of by direct reference.
