### ISSUE TITLE
System.FormatException: String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by wannabuild** [ParsePlatform/Parse-SDK-dotNET#64]
We're just using Parse for simple push notifications (for now), and we've gotten the following exception(s):

```
Package: com.myapp.alpha
Version: 1681
Android: 5.1.1
Manufacturer: samsung
Model: SM-G920I
Date: 05/11/2015 13:03:18

System.FormatException: String was not recognized as a valid DateTime.
			at System.DateTimeParse.ParseExact(System.String_s__System.String_format__System.Globalization.DateTimeFormatInfo_dtfi__DateTimeStyles_style.args:1337)
			at System.DateTime.ParseExact(System.String_s__System.String_format__IFormatProvider_provider.args:1337)
			at com.myapp.alpha.Parse.Internal.ParseDecoder.ParseDate(System.String_input.args:1337)
			at com.myapp.alpha.Parse.Internal.ParseObjectCoder.<Decode>b__3(System.Object_obj.args:1337)
			at com.myapp.alpha.eTime>>:invoke_TResult_T(object.args:1337)
			at com.myapp.alpha.Parse.Internal.ParseObjectCoder.extractFromDictionary[Nullable`1](IDictionary`2_data__System.String_key__System.Func`2_action.args:1337)
                        at com.myapp.alpha.Parse.Internal.ParseObjectCoder.Decode(IDictionary`2_data__Parse.Internal.ParseDecoder_decoder.args:1337)
			at com.myapp.alpha.Parse.Internal.ParseObjectController.<SaveAsync>b__2(System.Threading.Tasks.Task`1_t.args:1337)
			at com.myapp.alpha.Parse.Internal.InternalExtensions+<>c__DisplayClass1`2[System.Tuple`2[System.Net.HttpStatusCode,System.Collections.Generic.IDictionary`2[S\
ystem.String,System.Object]],Parse.Internal.IObjectState].<OnSuccess>b__0(System.Threading.Tasks.Task_t.args:1337)
			at com.myapp.alpha.Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[Parse.Internal.IObjectState].<OnSuccess>b__6(System.Threading.Tasks.Task_t.args:133\
7)
              		at System.Threading.Tasks.ContinuationResultTaskFromTask`1[System.Threading.Tasks.Task`1[Parse.Internal.IObjectState]].InnerInvoke(.args:1337)
			at System.Threading.Tasks.Task.Execute(.args:1337)
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
			at com.myapp.alpha.Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[System.Threading.Tasks.Task].<OnSuccess>b__6(System.Threading.Tasks.Task_t.args:133\
7)
              		at System.Threading.Tasks.ContinuationResultTaskFromTask`1[System.Threading.Tasks.Task`1[System.Threading.Tasks.Task]].InnerInvoke(.args:1337)
			at System.Threading.Tasks.Task.Execute(.args:1337)
```

And all we do with Parse (for now) is the following:

```
public override void OnCreate()
{
     base.OnCreate();

     RegisterActivityLifecycleCallbacks(new MyLifecycleHandler());

     ...

     var info = ParseHelper.GetInfo(BuildType);
     ParseClient.Initialize(info.AppId, info.NetKey);
     var installation = ParseInstallation.CurrentInstallation;
     installation.SaveAsync();
     ParsePush.ParsePushNotificationReceived += ParsePush.DefaultParsePushNotificationReceivedHandler;
            
}
```

We don't use anything else from Parse... Just the above.  Speaking of which, I feel bit funny letting the Save.Async() call dangle like that, but don't really want to await it either.  Anyhow, this doesn't always happen, but does happen sometimes.  I think the fix would be to go through the code and try/catch around parsing date/time strings.

**Comment by richardjrossiii** [comment]
That seems odd. It would appear that the server is giving back Dates formatted improperly. I assume the answer is no, but are you using CloudCode anywhere? We've seen issues with CloudCode returning improper dates in the past (#38), but never from the main SDK.

We can definitely add better error handling code for cases where the server returns invalid data, but if it's consistently returning bad data, then it probably is a backend issue, which should be reported at http://parse.com/help.

**Comment by habermeier** [comment]
@richardjrossiii No I don't use CloudCode anywhere.  The only Parse SDK related call I make is in OnCreate() -- the bare minimum to get push notifications going.  

I do not get this error a lot.  I just saw it once or twice.  But I did get it.  Well -- really, someone in India got it.  There could be 2 possibilities I can immagine:  a) a transient bug on the server side, or b) a network related failure that isn't getting caught (or partially caught) and a null or empty string makes its way to the code that is trying to figure out the date.  Pure speculation on my part of course.

All  I know is what I have there...

**Comment by habermeier** [comment]
@richardjrossiii do you still need more information from me on this?  I think it's a bug in the SDK or possibly the server.  The crash happened in India... is it possible there is a formatting issue around localized date representation?

**Comment by richardjrossiii** [comment]
@habermeier anything's possible. I'll check into locale, and mark this as under investigation for now. If I can't get it to fail, I'll have to mark it as 'needs more info again'.

**Comment by richardjrossiii** [comment]
After testing with my locale set to Indian, our dates are still parsing correctly, at least with all the examples I have tried.

To investigate this further I really need the string that's failing to parse, unfortunately.

**Comment by habermeier** [comment]
@richardjrossiii I guess the only way to do that would be to add a try / catch block around

```
    internal static DateTime ParseDate(string input) {
      // TODO(hallucinogen): Figure out if we should be more flexible with the date formats
      // we accept.
      return DateTime.ParseExact(input,
          ParseClient.DateFormatString,
          CultureInfo.InvariantCulture);
    }
```

and log the problem there.  But given this is likely coming from:

```
        if (typeString == "Date") {
          return ParseDate(dict["iso"] as string);
        }
```

That means dict["iso"] is either not set, or not set to something valid, which is unlikely to be a core issue with the SDK itself.  Bottom line though is this:  Why would it be OK to let the SDK crash if the server sent something bad to a client?  

As an SDK user, I'd rather know that my app won't crash even if there is a temporary problem with the parse service.  Bottom line, if you allow for there to be a possible problem with the server side, how would you protect my app from crashing?  What should it do when it's expecting a date, but there is either no (or no valid date) coming from the server.

Crashing my app isn't the right answer.  So I guess my point is:  It kind of doesn't matter what the string was.  What if I had logged it myself, and told you it was an empty string.  Or a null pointer?  Or a malformed date format.

Even if there was a bug upstream on the server side that could be fixed, there is no guarantee that in the future there won't be a bug introduced that screws this up.  

The SDK should protect against crashing.  Period.

**Comment by richardjrossiii** [comment]
The solution here is not to just try-catch. DateTime is a struct in C#, so what date could we *possibly* return that makes sense for an arbitrary invalid date field?

I firmly believe that crashing *is* the right response in this case, because that allows us to properly handle the problem rather than just treating the symptoms.

Besides - we're operating in the context of a `Task` here anyway - you should just be able to continue on the result of `SaveAsync()`, and as long as you read the result of `task.Exception`, the tasks library will not re-throw the exception.

**Comment by habermeier** [comment]
Bottom line if someone on the server side team checks in bad code, and it goes unnoticed, your SDK could end up crashing millions of clients over hundreds of different apps.  As an app developer I don't look kindly on SDK's that crash my app in unexpected ways.  Sure, I can put a try-catch around all your API's, and I guess I'll do just that.

Maybe you should add a try / catch block to your documentation as well.

Of course if you tell everyone that SaveAsync() can crash anyhow it likes, and everyone puts try/catches around the code, then you won't get notified that it crashed either.  So your solution is to make the user of the SDK protect against the component crashing, and if everyone wraps the call in a try/catch you just complicated the life of the user of the SDK for no benefit.  If indeed we should be try/catching SaveAsync() you might as well do it in the library itself.

I'm not in control of what your server does.  Basically ANY networking operation can fail anyhow it wants.  It's not reasonable to crash if you get an unexpected thing back from the server.  That's just not good SDK design.  Sorry.

I still think you got a bug here, and I still believe the SDK should not crash if it can at all be avoided because crashing isn't the experience the end user wants.

**Comment by lacker** [comment]
If the server actually returned bad data, then I agree with @habermeier, that the correct response for the SDK is to throw a Parse exception rather than some other one. That way it would get treated just like a networking error, or a Parse outage. That's what we do if e.g. the server doesn't return valid json. (I think.)

However, that isn't clear to me. Did the server actually return a bad timestamp?

**Comment by richardjrossiii** [comment]
@lacker In this scenario we don't know. There apparently was a one-off non-reproducible exception that was thrown (and caught by parse already, to be noted), and because the user did not check the result of the SaveAsync() task, the app crashes.

This isn't something that can t easily be fixed, as it's a feature of the .NET Tasks framework, to rethrow an unhandled exception like that.

**Comment by habermeier** [comment]
@richardjrossiii My point is that the SDK ought not throw unexpected stuff if the server gives it unexpected data.  It doesn't really matter what the string was, other than that it was a bad string.  What difference does it make if it was a truncated date string or an empty string?  It doesn't really prove anything other than that something went wrong upstream -- something not in my control.

It should be easy to reproduce the problem if you produce a bad data and feed it to the SDK.

Of course you want to make sure the server works -- you ought to just not take it out on our end users when it doesn't.  Seriously, if the correct usage of the API is to wrap every call in a try/catch *you really should add that into your bootstrap documentation*. 

Just because the server hardly ever produce bad data, doesn't make it OK to crash when it fails to do so.  You should not trust that the data is OK from your server.

I was not expecting SaveAsync() to throw this kind of exception.  It's not like I even know what's going on under the covers... (until this crash happened).  I'd say this is still an SDK bug, regardless how difficult you think it is to fix.

**Comment by richardjrossiii** [comment]
@habermeier I think you may be missing the point. You do not need to wrap anything in a try-catch call. All that is required is to continue upon the task like this:

    installation.SaveAsync().ContinueWith(t => {
        if (t.Faulted) {
           Debug.Writeline(t.Exception);
        }
    });

This is the [.NET standard way of dealing with task exceptions](https://msdn.microsoft.com/en-us/library/dd997415(v=vs.110).aspx). 

It may be a flawed API, but it's not our API that's flawed, its Microsofts.

The Parse SDK itself will **never** crash directly on an asynchronous call. The exceptions will always get caught by the Tasks framework. Period.

However, if you don't read from that exception, the **Tasks Framework** will re-throw the exception *not* Parse.

**Comment by habermeier** [comment]
@richardjrossiii Yes, you can use `ContinueWith`.  You can also await the task and try/catch.  Essentially the same difference.  Granted using ContinueWith, you don't have to be in an async method yourself, which is easier to drop in on some places... but that's not really my point.  That's just the mechanics of how you deal with having to catch the exception.

So let me ask you this:  Is it standard practice that I have to expect exceptions getting thrown by any/all API calls to Parse?  Because if that is the case, then the bug isn't necessarily an SDK issue, but a documentation issue.  **I'd suggest adding the appropriate exception handling into all of your code samples.** 

But if that's not the case, my point is that if the server produces bad data for the SDK for any reason, why would it not be treated internally by Parse like any other issue between the parse server and the SDK?  (bad networking, etc.)

**Comment by habermeier** [comment]
Ok, was able to reproduce.  The problem is that we are getting an unexpected time string, as per your `DateFormatString`.  When it throws that exception, it does it when there isn't a 3 digit fractional second number.  At least I assume that is what that is.

```
            {
                
                const string DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'";

                var goodDate = DateTime.ParseExact("2015-11-16T18:45:50.186Z", DateFormatString, CultureInfo.InvariantCulture);
                Console.WriteLine("date is: {0}", goodDate);

                try { 
                    var badDate  = DateTime.ParseExact("2015-11-17T20:07:19.14Z", DateFormatString, CultureInfo.InvariantCulture);
                    Console.WriteLine("date is: {0}", badDate);
                } catch (Exception ex) {
                    Console.WriteLine("Exception: {0}", ex);
                }
                
            }
```

My guess is that whatever is producing the timestamp is suppressing any trailing '0's on the fractional second, which doesn't happen all the time, but often enough.  I'm wondering why I'm the only one running into this.  How many people are actually using this particular SDK I wonder...

I mean, there is nothing special about our use case.  Anyhow, looks like that is the

**Comment by richardjrossiii** [comment]
Yep. Just talked with some other team members, apparently this is a super old bug that we've seen before in the back-end, and it's surprising that it's popping up again. I'll attempt to make the client less strict on the trailing zeroes.
